// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService exposes session state and actions to the React frontend via Wails bindings.
 * 
 * Wails v3 auto-generates TypeScript stubs in frontend/bindings/ from exported methods.
 * Rules for binding generation:
 *   - The struct and all bound methods must be exported.
 *   - Method parameters and return values must be JSON-serialisable (or error).
 *   - Methods named ServiceStartup / ServiceShutdown are treated as lifecycle hooks, not bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as registry$0 from "./internal/registry/models.js";

/**
 * DismissSession removes a session from the registry (e.g. user manually closes a card).
 * 
 * The registry's onChange callback fires after removal, so the frontend receives an updated
 * "sessions-updated" event automatically — no additional round-trip needed.
 * @param {string} sessionKey
 * @returns {$CancellablePromise<void>}
 */
export function DismissSession(sessionKey) {
    return $Call.ByID(1122257593, sessionKey);
}

/**
 * JumpToTerminal brings the terminal window/tab that owns sessionKey to the foreground.
 * 
 * Looks up the session by key, then delegates to terminal.Jump which handles
 * iTerm2 (via ITermSessionID or TTY) and Terminal.app (via TTY) via osascript.
 * 
 * Returns an error string visible in the frontend Toast on failure (e.g. permission denied
 * on first run — macOS will prompt the user for Automation access).
 * @param {string} sessionKey
 * @returns {$CancellablePromise<void>}
 */
export function JumpToTerminal(sessionKey) {
    return $Call.ByID(1609897880, sessionKey);
}

/**
 * ListSessions returns all sessions sorted by UpdatedAt descending (newest first).
 * 
 * Used by the frontend for:
 *   - Initial data load on panel open.
 *   - Manual refresh (pull-to-refresh).
 * 
 * Real-time updates are pushed via the "sessions-updated" Wails event; polling is not needed.
 * @returns {$CancellablePromise<(registry$0.Session | null)[]>}
 */
export function ListSessions() {
    return $Call.ByID(1911720108).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = registry$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
