// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// STUB: SettingsService Go bindings not yet wired. Wails will overwrite this file.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetSettings returns the current settings configuration.
 * @returns {$CancellablePromise<any>}
 */
export function GetSettings() {
    return $Call.ByID(0);
}

/**
 * UpdateSettings persists new settings values.
 * @param {any} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(cfg) {
    return $Call.ByID(0, cfg);
}
