// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "../event/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Session represents an active agent session.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("Key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Key"] = "";
        }
        if (!("Agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Agent"] = "";
        }
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("CWD" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CWD"] = "";
        }
        if (!("TTY" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TTY"] = "";
        }
        if (!("TermProgram" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TermProgram"] = "";
        }
        if (!("ITermSessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ITermSessionID"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("AttentionLevel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AttentionLevel"] = "";
        }
        if (!("AgentLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AgentLabel"] = "";
        }
        if (!("SessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SessionID"] = "";
        }
        if (!("LastEvent" in $$source)) {
            /**
             * @member
             * @type {event$0.AgentEvent | null}
             */
            this["LastEvent"] = null;
        }
        if (!("PendingTools" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: event$0.AgentEvent | null }}
             */
            this["PendingTools"] = {};
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LastEvent" in $$parsedSource) {
            $$parsedSource["LastEvent"] = $$createField11_0($$parsedSource["LastEvent"]);
        }
        if ("PendingTools" in $$parsedSource) {
            $$parsedSource["PendingTools"] = $$createField12_0($$parsedSource["PendingTools"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = event$0.AgentEvent.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
