// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * AgentEvent is the single cross-layer data structure.
 * Bridge fills all fields; server and UI are read-only consumers.
 */
export class AgentEvent {
    /**
     * Creates a new AgentEvent instance.
     * @param {Partial<AgentEvent>} [$$source = {}] - The source object to create the AgentEvent.
     */
    constructor($$source = {}) {
        if (!("agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("tty" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tty"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("term_program" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["term_program"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["iterm_session_id"] = undefined;
        }
        if (!("event_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event_type"] = "";
        }
        if (!("tool_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_name"] = "";
        }
        if (!("tool_use_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_use_id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("content_raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content_raw"] = "";
        }
        if (!("agent_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["permission_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["raw_payload"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentEvent(/** @type {Partial<AgentEvent>} */($$parsedSource));
    }
}

/**
 * SessionStatus is the single source of truth for session UX state.
 * Values are mutually exclusive; UI renders one tag per card.
 * @readonly
 * @enum {string}
 */
export const SessionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * active, no user action needed
     */
    StatusWorking: "working",

    /**
     * user action required (any reason)
     */
    StatusWaiting: "waiting",

    /**
     * ended cleanly
     */
    StatusDone: "done",

    /**
     * ended with failure
     */
    StatusError: "error",
};
