// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("opacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("hotkey_toggle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hotkey_toggle"] = "";
        }
        if (!("notification_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notification_level"] = "";
        }
        if (!("popup_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["popup_width"] = 0;
        }
        if (!("popup_pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["popup_pinned"] = false;
        }
        if (!("session_load_hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session_load_hours"] = 0;
        }
        if (!("notification_events" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["notification_events"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notification_events" in $$parsedSource) {
            $$parsedSource["notification_events"] = $$createField8_0($$parsedSource["notification_events"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
