// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DataStats holds database statistics for display in settings UI.
 */
export class DataStats {
    /**
     * Creates a new DataStats instance.
     * @param {Partial<DataStats>} [$$source = {}] - The source object to create the DataStats.
     */
    constructor($$source = {}) {
        if (!("db_size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["db_size_bytes"] = 0;
        }
        if (!("event_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["event_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataStats(/** @type {Partial<DataStats>} */($$parsedSource));
    }
}
