// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionBinding exposes session state and actions to the React frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";

/**
 * DismissSession removes a session from the registry.
 * @param {string} sessionKey
 * @returns {$CancellablePromise<void>}
 */
export function DismissSession(sessionKey) {
    return $Call.ByID(1311239598, sessionKey);
}

/**
 * JumpToTerminal brings the terminal window/tab to the foreground.
 * @param {string} sessionKey
 * @returns {$CancellablePromise<void>}
 */
export function JumpToTerminal(sessionKey) {
    return $Call.ByID(1000144375, sessionKey);
}

/**
 * ListSessions returns all sessions sorted by UpdatedAt descending.
 * @returns {$CancellablePromise<(session$0.Session | null)[]>}
 */
export function ListSessions() {
    return $Call.ByID(423317127).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = session$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
