// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsBinding exposes user settings to the React frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../infra/config/models.js";

/**
 * GetSettings returns the current settings.
 * @returns {$CancellablePromise<config$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(3093673318).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateSettings saves new settings, broadcasts change event, and triggers onChange.
 * @param {config$0.Settings} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(cfg) {
    return $Call.ByID(3689992101, cfg);
}

// Private type creation functions
const $$createType0 = config$0.Settings.createFrom;
