// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowBinding exposes popup window controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenSettings shows the settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(1614238357);
}

/**
 * SetPinned toggles always-on-top and persists state.
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetPinned(pinned) {
    return $Call.ByID(1127898306, pinned);
}

/**
 * SetPopupWidth persists the user-adjusted width.
 * @param {number} width
 * @returns {$CancellablePromise<void>}
 */
export function SetPopupWidth(width) {
    return $Call.ByID(996906110, width);
}
