// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../entity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * Session represents an active agent session.
 * 
 * PendingTools is internal state-machine bookkeeping for the tracker. It is
 * excluded from JSON output (json:"-") because (a) the frontend does not
 * consume it and (b) it is reset/mutated frequently inside TrackEvent —
 * exposing it to the marshaler would race with the next TrackEvent.
 * 
 * snapshotLocked() additionally returns a deep copy of every Session and its
 * maps so consumers can hold the snapshot indefinitely (Wails Event.Emit
 * dispatches Marshal asynchronously) without risking concurrent mutation.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("Key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Key"] = "";
        }
        if (!("Agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Agent"] = "";
        }
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("CWD" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CWD"] = "";
        }
        if (!("TTY" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TTY"] = "";
        }
        if (!("TermProgram" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TermProgram"] = "";
        }
        if (!("ITermSessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ITermSessionID"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {entity$0.SessionStatus}
             */
            this["Status"] = entity$0.SessionStatus.$zero;
        }
        if (!("AgentLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AgentLabel"] = "";
        }
        if (!("SessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SessionID"] = "";
        }
        if (!("LastEvent" in $$source)) {
            /**
             * @member
             * @type {entity$0.AgentEvent | null}
             */
            this["LastEvent"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LastEvent" in $$parsedSource) {
            $$parsedSource["LastEvent"] = $$createField10_0($$parsedSource["LastEvent"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = entity$0.AgentEvent.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
